# Generated by Django 5.0.7 on 2024-07-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='team_members',
            new_name='no_of_team_members',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='college_roll_number',
            new_name='roll_number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='team_lead_email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='team_lead_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='college',
            field=models.CharField(default=1993, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='team_lead_mobile_no',
            field=models.CharField(default=1993, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='homepage.registration')),
            ],
        ),
    ]
