# Generated by Django 5.0.7 on 2024-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_registration_photo_registration_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='college',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='roll_number',
            new_name='college_roll_number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='no_of_team_members',
            new_name='team_members',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_lead_email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_lead_mobile_no',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_lead_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default=1993, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(default=1993, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=1993, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
