# Generated by Django 5.0.7 on 2024-07-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_college_registration_college_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('roll_number', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=100)),
                ('team_size', models.IntegerField()),
                ('team_member_names', models.TextField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
